# Generated by Django 3.1.2 on 2020-10-25 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryConditionField_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Entry Conditions Field #2 ',
                'verbose_name_plural': 'Entry Conditions Field #2 ',
            },
        ),
        migrations.CreateModel(
            name='EntryConditionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=100, verbose_name='Select Field')),
            ],
            options={
                'verbose_name': 'Entry Conditions Field #1',
                'verbose_name_plural': 'Entry Conditions Field #1 ',
            },
        ),
        migrations.CreateModel(
            name='RiskManagementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Risk Management Condition',
                'verbose_name_plural': 'Risk Management Condition',
            },
        ),
        migrations.CreateModel(
            name='TrailConditionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=100)),
                ('field_2', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'verbose_name': 'Trail Condition Field #1',
                'verbose_name_plural': 'Trail Condition Field #1 ',
            },
        ),
        migrations.CreateModel(
            name='TrailConditionLevel_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('field_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algobt.trailconditionmodel')),
            ],
            options={
                'verbose_name': 'Trail Condition Level #1',
                'verbose_name_plural': 'Trail Condition Level #1',
            },
        ),
        migrations.CreateModel(
            name='EntryConditionLevel_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CondOption', models.CharField(max_length=100)),
                ('level_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algobt.entryconditionmodel')),
            ],
            options={
                'verbose_name': 'Entry Condition Level #2',
                'verbose_name_plural': 'Entry Condition Level #2',
            },
        ),
        migrations.CreateModel(
            name='EntryConditionLevel_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('level_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algobt.entryconditionmodel')),
            ],
            options={
                'verbose_name': 'Entry Condition Level #1',
                'verbose_name_plural': 'Entry Condition Level #1',
            },
        ),
        migrations.CreateModel(
            name='EntryConditionField_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('field_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algobt.entryconditionmodel')),
            ],
            options={
                'verbose_name': 'Entry Conditions Field #3',
                'verbose_name_plural': 'Entry Conditions Field #3',
            },
        ),
    ]
