# Generated by Django 3.1.2 on 2020-11-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algobt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdatamodel',
            old_name='User',
            new_name='username',
        ),
    ]
