# Generated by Django 3.1.2 on 2020-11-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algobt', '0002_auto_20201104_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdatamodel',
            options={'verbose_name_plural': 'Records'},
        ),
        migrations.AlterModelTable(
            name='userdatamodel',
            table='User Records',
        ),
    ]
